### ISSUE TITLE
Tracking issue for renaming rational types

### ISSUE THREAD

**Issue by FreskyZ** [FreskyZ/fff-lang#16]
Currently primitive numeric types include 3 kind

- `i*` for integral types
- `u*` for unsigned integral types
- `f*` for floating point types

the name of 'integral types' comes from `the values *are* integral', but the name of 'floating point types' is weird, it comes from 'the values are *represented* in floating point format', actually, it should be 'the values are *rational*'(which can be represented as devision of 2 integers)

so, I'd like to rename current `f32` and `f64` types to `r32` and `r64` type

it also solves the issue that `0x123f32` is parsed as valid hexadecimal literal as `i32` type (`bits32` in future), when new developers trying to write a 'hexadecimal floating point literal', they will be confused about that

- [ ] add new keywords
- [ ] update numeric literal parser, including parsing process, tests and error messages
- [ ] ~~update semantic analyzer's primitive type declarations~~ (old semantic analyzer do not exists!)
