### ISSUE TITLE
Tracking issue for format string feature

### ISSUE THREAD

**Issue by FreskyZ** [FreskyZ/fff-lang#23]
steps: 

- [x] new lexical interface include format string
- [ ] new lexical interface include format string segment formatter
- [ ] remove bit operators from syntax parser
- [ ] mark bit operators as reserved, add `?` as reserved, update `token.py` implementation at same time
- [ ] separated `lexical::LitValue` and `syntax::LitExpr` interface definition
- [ ] new lexical parser for format string literal, tests
- [ ] new syntax parser for format string literal, tests

closes #22, #18
