### ISSUE TITLE
Tracking issue for source code management update

### ISSUE THREAD

**Issue by FreskyZ** [FreskyZ/fff-lang#7]
required by #5 and #6 , new module design see [name-module.md](https://github.com/FreskyZ/fff-lang/blob/42bcb73fdb1317835d1196811b0e2b5b72d0b817/docs/name-module.md)

- [x] remove codemap legacy logics and update new logics
- [x] new lexical main and test driver
- [x] new syntax main and test driver
- [ ] message human friendly formatter
- [x] syntax human friendly formatter and comparer and integration test

**Comment by FreskyZ** [comment]
the message human friendly formatter currently do exists, at lowest usablity, although current source code managers and diagnostics collection is completely different than code at this issue's time, I think this issue is actually closed by recent commits
